apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-advanced-boilerplate0-config
  labels:
    app.kubernetes.io/name: ai-advanced-boilerplate0
data:
  API_URL: 'REPLACE_WITH_API_URL'
  INSTANCE_DOMAIN: 'api.topia.io'
  INSTANCE_PROTOCOL: 'https'
  INTERACTIVE_KEY: 'REPLACE_WITH_REAL_INTERACTIVE_KEY'
  NODE_ENV: 'production'
